name: fnx_ui
description: A web app that uses AngularDart Components
version: 3.5.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^7.0.1
  angular_forms: ^4.0.1
  angular_router: ^3.0.1
  meta: any
  i69n: ^2.0.1
  intl: ^0.17.0
  async: any

dev_dependencies:
  angular_test: ^4.0.1
  build_test: ^2.1.4
  lints: ^1.0.1
  test: ^1.18.0
  sass_builder: ^2.1.4
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1