include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false

  errors:
    uri_has_not_been_generated: ignore
  # Angular plugin support is in beta. You're welcome to try it and report
  # issues: https://github.com/dart-lang/angular_analyzer_plugin/issues
  plugins:
    - angular
