name: fnx_ui_doc
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fnx_ui:
    path: ../fnx_ui/

dev_dependencies:
  angular: ^7.0.1
  sass_builder: ^2.1.4
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
