name: fnx_ui_doc
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fnx_ui:
    path: ../fnx_ui/

dev_dependencies:
  angular: ^6.0.1
  sass_builder: ^2.1.3
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=2.12.0 <3.0.0"
