List<String> randomStrings = [
  "The Beatles",
  "Bob Dylan",
  "Elvis Presley",
  "The Rolling Stones",
  "Chuck Berry",
  "Jimi Hendrix",
  "James Brown",
  "Little Richard",
  "Aretha Franklin",
  "Ray Charles",
  "Bob Marley",
  "The Beach Boys",
  "Buddy Holly",
  "Led Zeppelin",
  "Stevie Wonder",
  "Sam Cooke",
  "Muddy Waters",
  "Marvin Gaye",
  "The Velvet Underground",
  "Bo Diddley",
  "Otis Redding",
  "U2",
  "Bruce Springsteen",
  "Jerry Lee Lewis",
  "Fats Domino",
  "The Ramones",
  "Nirvana",
  "Prince",
  "The Clash",
  "Johnny Cash",
  "Smokey Robinson & The Miracles",
  "The Everly Brothers",
  "Neil Young",
  "Michael Jackson",
  "Madonna",
  "Roy Orbison",
  "John Lennon",
  "David Bowie",
  "Simon & Garfunkel",
  "The Doors",
  "Van Morrison",
  "Sly & the Family Stone",
  "Public Enemy",
  "The Byrds",
  "Janis Joplin",
  "Patti Smith",
  "Run-D.M.C.",
  "Elton John",
  "The Band",
  "Pink Floyd",
  "The Allman Brothers Band",
  "Queen",
  "Eric Clapton",
  "Grateful Dead",
  "Parliament-Funkadelic",
  "Aerosmith",
  "Grateful Dead",
  "Sex Pistols",
  "Louis Jordan",
  "Aerosmith",
  "Tina Turner",
  "Metallica",
  "The Police",
  "Frank Zappa",
  "AC/DC",
  "Radiohead",
  "Hank Williams",
  "The Eagles",
  "The Shirelles",
  "Beastie Boys",
  "The Stooges",
  "The Four Tops",
  "Elvis Costello",
  "The Drifters",
  "Eminem	Creedence Clearwater Revival",
  "N.W.A.	Eminem",
  "James Taylor",
  "Black Sabbath",
  "Tupac",
  "Gram Parsons",
  "Miles Davis",
  "Jay-Z",
  "The Yardbirds",
  "Carlos Santana",
  "Ricky Nelson	Tom Petty",
  "Guns N' Roses",
  "Booker T. & the M.G.'s",
  "Nine Inch Nails",
  "Lynyrd Skynyrd",
  "Martha & The Vandellas	Diana Ross and the Supremes",
  "Diana Ross and the Supremes",
  "R.E.M.",
  "Talking Heads",
  "Weird Al Yankovic",
];

List<String> randomLongStrings = List.generate(100, (i) {
  int a = (i * 17 + 31) % randomStrings.length;
  print(a);
  String one = randomStrings[a];
  a = (a * 17 + 31) % randomStrings.length;
  print(a);
  String two = randomStrings[a];
  return "$one vs. $two";
});
